### ISSUE TITLE
Pasar componentes de page.module.ts a pevento.module.ts

### ISSUE THREAD

**Issue by javiermatias** [javiermatias/MisEventos#16]
![image](https://user-images.githubusercontent.com/12036330/61254691-bf8b5780-a73b-11e9-9ecf-efca393338bb.png)

**Comment by lucasgonzalezm** [comment]
Que significa peventos? Pages Eventos? Que se gana haciendo esto?

**Comment by javiermatias** [comment]
mi idea es modularizar un poco mas el código. Ahora esta todo en page.module.ts. Pero en page.module.ts esta todo lo del template. Me gustaría al menos poder sacar los componentes que están en la carpeta mis-eventos y colocarlo en peventos.module.ts. peventos es, porque ya existe un modulo que se llama eventos.module.ts

**Comment by javiermatias** [comment]
Cerrado por falta de tiempo
